# Constants
CHAR_WHITESPACE = 1
CHAR_DELIMITER = 2
CHAR_REGULAR = 3

CONTEXT_NONE = 1
CONTEXT_OBJ = 2
CONTEXT_XREF = 3
CONTEXT_TRAILER = 4

PDF_ELEMENT_COMMENT = 1
PDF_ELEMENT_INDIRECT_OBJECT = 2
PDF_ELEMENT_XREF = 3
PDF_ELEMENT_TRAILER = 4
PDF_ELEMENT_STARTXREF = 5
PDF_ELEMENT_MALFORMED = 6

pdfObjTypeD = {   
    1: "PDF_ELEMENT_COMMENT",
    2: "PDF_ELEMENT_INDIRECT_OBJECT",
    3: "PDF_ELEMENT_XREF",
    4: "PDF_ELEMENT_TRAILER",
    5: "PDF_ELEMENT_STARTXREF",
    6: "PDF_ELEMENT_MALFORMED",

    "PDF_ELEMENT_COMMENT":          1,
    "PDF_ELEMENT_INDIRECT_OBJECT":  2,
    "PDF_ELEMENT_XREF":             3,
    "PDF_ELEMENT_TRAILER":          4,
    "PDF_ELEMENT_STARTXREF":        5,
    "PDF_ELEMENT_MALFORMED":        6 
}
